name: assesment_motio
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  adaptive_theme: ^3.7.0
  appflowy_board: ^0.1.2
  bloc: ^9.0.0
  collection: ^1.19.1
  currency_formatter: ^2.2.3
  dropdown_button2: ^2.3.9
  equatable: ^2.0.7
  firebase_auth: ^5.5.3
  firebase_core: ^3.13.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_secure_storage: ^9.2.4
  google_fonts: ^6.2.1
  hive_flutter: ^1.1.0
  intl: ^0.20.2
  loader_overlay: ^5.0.0
  logger: ^2.5.0
  meta: ^1.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  change_app_package_name: ^1.5.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.15

flutter:
  uses-material-design: true
